version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4

    working_directory: ~/project

    steps:
      - checkout
      - run: npm install
      - run: npm test

      - store_test_results:
          path: "./reports/junit.xml"

      - store_artifacts:
          path: "./test-report.html"
