version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Npm Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/

      - store_test_results:
          path: ./reports/junit/

      - store_artifacts:
          path: ./test-report.html
